name: nhanes-sleep-cvd
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - notebook
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - statsmodels
  - seaborn
  - nbformat
  - pip
  - pip:
      - xgboost
